export const cropPriceData = {
    // 🌾 Cereals & Millets
    Rice: { basePrice: 38, peakMonths: ["October", "November"], lowMonths: ["April", "May"] },
    Wheat: { basePrice: 32, peakMonths: ["March", "April"], lowMonths: ["August"] },
    Maize: { basePrice: 28, peakMonths: ["September"], lowMonths: ["January"] },
    Barley: { basePrice: 30, peakMonths: ["March"], lowMonths: ["July"] },
    Jowar: { basePrice: 29, peakMonths: ["October"], lowMonths: ["June"] },
    Bajra: { basePrice: 26, peakMonths: ["September"], lowMonths: ["February"] },
    Ragi: { basePrice: 34, peakMonths: ["November"], lowMonths: ["May"] },
    FoxtailMillet: { basePrice: 42, peakMonths: ["October"], lowMonths: ["June"] },
    LittleMillet: { basePrice: 44, peakMonths: ["October"], lowMonths: ["July"] },
    KodoMillet: { basePrice: 40, peakMonths: ["September"], lowMonths: ["June"] },
    BarnyardMillet: { basePrice: 46, peakMonths: ["October"], lowMonths: ["July"] },
    ProsoMillet: { basePrice: 43, peakMonths: ["September"], lowMonths: ["June"] },
    PearlMillet: { basePrice: 27, peakMonths: ["September"], lowMonths: ["January"] },
    FingerMillet: { basePrice: 36, peakMonths: ["November"], lowMonths: ["May"] },
    EmmerWheat: { basePrice: 35, peakMonths: ["March"], lowMonths: ["August"] },

    // 🌱 Pulses
    Chickpea: { basePrice: 62, peakMonths: ["February"], lowMonths: ["July"] },
    PigeonPea: { basePrice: 70, peakMonths: ["January"], lowMonths: ["June"] },
    GreenGram: { basePrice: 68, peakMonths: ["March"], lowMonths: ["August"] },
    BlackGram: { basePrice: 66, peakMonths: ["April"], lowMonths: ["September"] },
    Lentils: { basePrice: 68, peakMonths: ["February"], lowMonths: ["July"] },
    Cowpea: { basePrice: 60, peakMonths: ["March"], lowMonths: ["August"] },
    FieldPea: { basePrice: 55, peakMonths: ["February"], lowMonths: ["July"] },
    HorseGram: { basePrice: 50, peakMonths: ["January"], lowMonths: ["June"] },
    MothBean: { basePrice: 58, peakMonths: ["March"], lowMonths: ["August"] },
    Rajma: { basePrice: 90, peakMonths: ["January"], lowMonths: ["July"] },

    // 🌻 Oilseeds
    Groundnut: { basePrice: 55, peakMonths: ["October"], lowMonths: ["March"] },
    Mustard: { basePrice: 50, peakMonths: ["February"], lowMonths: ["August"] },
    Soybean: { basePrice: 45, peakMonths: ["September"], lowMonths: ["January"] },
    Sunflower: { basePrice: 52, peakMonths: ["March"], lowMonths: ["July"] },
    Sesame: { basePrice: 75, peakMonths: ["October"], lowMonths: ["May"] },
    Linseed: { basePrice: 48, peakMonths: ["February"], lowMonths: ["July"] },
    Castor: { basePrice: 60, peakMonths: ["October"], lowMonths: ["June"] },
    Safflower: { basePrice: 54, peakMonths: ["March"], lowMonths: ["August"] },
    NigerSeed: { basePrice: 58, peakMonths: ["September"], lowMonths: ["June"] },
    Rapeseed: { basePrice: 52, peakMonths: ["February"], lowMonths: ["August"] },

    // 🌶 Spices
    Turmeric: { basePrice: 120, peakMonths: ["February", "March"], lowMonths: ["July"] },
    ChilliDry: { basePrice: 140, peakMonths: ["March"], lowMonths: ["August"] },
    CorianderSeed: { basePrice: 90, peakMonths: ["January"], lowMonths: ["June"] },
    Cumin: { basePrice: 210, peakMonths: ["March"], lowMonths: ["July"] },
    Fenugreek: { basePrice: 85, peakMonths: ["February"], lowMonths: ["August"] },
    Pepper: { basePrice: 520, peakMonths: ["January"], lowMonths: ["June"] },
    Cardamom: { basePrice: 900, peakMonths: ["November"], lowMonths: ["May"] },
    Clove: { basePrice: 780, peakMonths: ["December"], lowMonths: ["June"] },
    GingerDry: { basePrice: 160, peakMonths: ["February"], lowMonths: ["August"] },
    Nutmeg: { basePrice: 600, peakMonths: ["December"], lowMonths: ["June"] },

    // 🧵 Commercial / Plantation
    Cotton: { basePrice: 60, peakMonths: ["November"], lowMonths: ["June"] },
    Jute: { basePrice: 42, peakMonths: ["September"], lowMonths: ["February"] },
    Sugarcane: { basePrice: 35, peakMonths: ["December"], lowMonths: ["April"] },
    Tea: { basePrice: 180, peakMonths: ["May"], lowMonths: ["December"] },
    Coffee: { basePrice: 220, peakMonths: ["January"], lowMonths: ["July"] },
    Rubber: { basePrice: 160, peakMonths: ["November"], lowMonths: ["April"] },
    Tobacco: { basePrice: 95, peakMonths: ["February"], lowMonths: ["August"] },
    Arecanut: { basePrice: 320, peakMonths: ["January"], lowMonths: ["June"] },
    CoconutCopra: { basePrice: 130, peakMonths: ["December"], lowMonths: ["July"] },
    Indigo: { basePrice: 75, peakMonths: ["September"], lowMonths: ["March"] },
};
